config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  resources :people

end

app/models/person.rb
require 'active_record/salesforce'

class Person < ActiveRecord::Base
  include ActiveRecord::Salesforce::Base

  attr_accessor :company_to_use

  validates_presence_of :name, :last_name, :company

  after_save :set_to_salesforce

  salesforce_object :Lead

  #SalesForce_attribute, RDStation_attribute
  map_attribute :FirstName      , :name
  map_attribute :LastName       , :last_name
  map_attribute :Company        , :company
  map_attribute :Email          , :email
  map_attribute :JobTitle__c    , :job_title
  map_attribute :Phone          , :phone
  map_attribute :Website        , :website
  map_attribute :OwnerId        , :owner_id
  map_attribute :IsConverted    , :converted
  map_attribute :IsUnreadByOwner, :unread_by_owner

  def initialize(attributes={})
    super
    @converted ||= false
    @unread_by_owner ||= false
  end

  private
  def set_to_salesforce
    @config_file = YAML.load_file("config/salesforce.yml")
    save_in_salesforce @config_file[company_to_use]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :last_name, :company, :email, :job_title, :phone, :website, :owner_id, :converted, :unread_by_owner, :company_to_use)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RdstationSalesforceExample" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">RdstationSalesforceExample</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => "form-horizontal person" } do |f| %>

    <% if @person.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@person[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%= error_span(@person[:last_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :company, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :company, :class => 'form-control' %>
    </div>
    <%= error_span(@person[:company]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@person[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :job_title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :job_title, :class => 'form-control' %>
    </div>
    <%= error_span(@person[:job_title]) %>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@person[:phone]) %>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'form-control' %>
    </div>
    <%= error_span(@person[:website]) %>
  </div>

  <div class="checkbox">
    <%= f.label :converted , :class => 'control-label' do %>
      <%= f.check_box :converted %> <%= p 'converted' %>
    <% end %>
    <%= error_span(@person[:converted]) %>
  </div>

  <div class="checkbox">
    <%= f.label :unread_by_owner, :class => 'control-label' do %>
      <%= f.check_box :unread_by_owner %> <%= p 'unread by owner' %>
    <% end %>
    <%= error_span(@person[:unread_by_owner]) %>
  </div>

  <div class="control-group">
    <%= f.label :company_to_use, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :company_to_use, %w(resultados_digitais company_2), :class => 'form-control' %>
    </div>
    <%= error_span(@person[:owner_id]) %>
  </div>

  <div class="control-group margin-top-10">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            people_path, :class => 'btn btn-default' %>
  </div>

<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:company) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:job_title) %></th>
      <th><%= model_class.human_attribute_name(:converted) %></th>
      <th><%= model_class.human_attribute_name(:unread_by_owner) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.company %></td>
        <td><%= person.email %></td>
        <td><%= person.job_title %></td>
        <td><%= person.converted %></td>
        <td><%= person.unread_by_owner %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @person.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company) %>:</strong></dt>
  <dd><%= @person.company %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @person.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_title) %>:</strong></dt>
  <dd><%= @person.job_title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @person.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
  <dd><%= @person.website %></dd>
  <dt><strong><%= model_class.human_attribute_name(:owner_id) %>:</strong></dt>
  <dd><%= @person.owner_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:converted) %>:</strong></dt>
  <dd><%= @person.converted %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unread_by_owner) %>:</strong></dt>
  <dd><%= @person.unread_by_owner %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn btn-default'  %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>